### ISSUE TITLE
Add Link

### ISSUE THREAD

**Issue by ghost** [PolarComputer/Helium-UI2#1]
The `<a></a>` refrence has not been styled.

````css
a {
  text-decoration: underline;
  color: #148ff5;
}
````
