### ISSUE TITLE
Checkbox Not working.

### ISSUE THREAD

**Issue by ghost** [PolarComputer/Helium-UI2#3]

**Comment by ghost** [comment]
For some reason, in some places, the checkbox was working but on the login screen it wasn't I figured out it was the visibility of the input of the checkbox.
```` css
.checkbox input[type="checkbox"] {
  outline: 0;
  margin-right: 10px;
/*   visibility: hidden; */
}
````
