### ISSUE TITLE
Check box size

### ISSUE THREAD

**Issue by ghost** [PolarComputer/Helium-UI2#6]
Add/ Edit this code
```` css
.checkbox input[type="checkbox" i] {
    /* margin: 10px; */
    width: 22px;
    height: 22px;
    margin: 0;
}
````
