### ISSUE TITLE
Check Box text is to far off

### ISSUE THREAD

**Issue by ghost** [PolarComputer/Helium-UI2#9]
```` css
.checkbox label {
    margin: 15px 0px 10px 40px!important; /* Change this line the 40px */
    font-weight: 600;
    color: #333;
}
````
